version: "3.7"
services:
  #
  # Microservices
  #
  identity:
    build: ./identity-api
    image: alexandria-identity:latest
    restart: on-failure
    volumes:
      - api:/usr/src/identity/:rw
    ports:
      - 4000:8080
      - 3000:9090
    depends_on:
      - redis
      - jaeger
    networks:
      - alexandria-tier

  #
  # Infrastructure
  #
  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - 6380:6379
    networks:
      - alexandria-tier

  jaeger:
    image: jaegertracing/all-in-one
    restart: on-failure
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - alexandria-tier

  prometheus:
    image: prom/prometheus
    restart: on-failure
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./third-party/prometheus:/etc/prometheus:ro
      - prometheus-storage:/var/lib/prometheus
    networks:
      - alexandria-tier

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    networks:
      - alexandria-tier

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - alexandria-tier

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
      - jaeger
    restart: on-failure
    ports:
      - 9413:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - alexandria-tier

volumes:
  api:
    driver: local
  grafana-storage:
    driver: local
  prometheus-storage:
    driver: local

# Networks to be created to facilitate communication between containers
networks:
  alexandria-tier:
      driver: bridge